change default group
osism/ansible-playbooks pull request #437
Opened 2024-06-25 17:50 UTC by scoopex

close #436 

This pull request addresses #436.

I replaced the "all" group by `default(hosts_default_group|default('generic'))` with a regex replace.
I simply adjusted the defaults in the following way:
```
$ find . -type f -name "*.yml" -exec sed -i "~s,hosts: all,hosts: \"{{ default(hosts_default_group|default('generic')) }}\",g" {} \;
$ find . -type f -name "*.yml" -exec sed -i "~s,|default('all'),|default(hosts_default_group|default('generic')),g" {} \;
```
As I haven't been working on this for very long, it may well take a little more work, but perhaps we can dare to do so :-)

2024-06-25 18:03 UTC, scoopex commented
Sorry, i accidentally missed to push a rework.
Now it should be as intended.

@berendt ready for review

2024-06-25 18:11 UTC, scoopex commented
Damn, it seems that a chained "default" is not accepted by "ansible-lint" but valid.

2024-06-26 07:11 UTC, berendt requested changes

2024-06-26 07:12 UTC, berendt commented on playbooks/generic/facts.yml
> +  hosts: "{{ hosts_facts|default(hosts_default_group|default('generic')) }}"
We can also overwrite this with osism/defaults + hosts_facts parameter.

2024-06-26 07:12 UTC, berendt commented on playbooks/generic/dump-facts.yml
> +  hosts: "{{ hosts_facts|default(hosts_default_group|default('generic')) }}"
We can also overwrite this with osism/defaults + hosts_facts parameter.

2024-06-26 07:44 UTC, merged